### ISSUE TITLE
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in D:\xampp\htdocs\crud-php\read.php:18 Stack trace: #0 D:\xampp\htdocs\crud-php\read.php(18): mysqli_num_rows(false) #1 {main} thrown in D:\xampp\htdocs\crud-php\read.php on line 18

### ISSUE THREAD

**Issue by Akioooooo** [codingWithElias/php-crud#1]
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in D:\xampp\htdocs\crud-php\read.php:18 Stack trace: #0 D:\xampp\htdocs\crud-php\read.php(18): mysqli_num_rows(false) #1 {main} thrown in D:\xampp\htdocs\crud-php\read.php on line 18

**Comment by RodnyPHP** [comment]
> Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in D:\xampp\htdocs\crud-php\read.php:18 Stack trace: #0 D:\xampp\htdocs\crud-php\read.php(18): mysqli_num_rows(false) #1 {main} thrown in D:\xampp\htdocs\crud-php\read.php on line 18

Because in that file he forgot to add like back look, like `include "../db_conn.php";`, because another way it try to find it in the same map if you don't put in the front ../, ther in that code is only `include "db_conn.php";`

**Comment by nkanhhh2102** [comment]
Tìm lỗi trên
